'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const subjects=['Criminology','Business','IT'],activities=['Flashcards','Past papers','Note taking','Homework'],colours=['red','green','blue'],key='stride.v1';
const fresh=()=>({version:1,sessions:[],courses:[],tasks:[],plans:[],topics:[],rewards:[],goal:300});
let data=fresh();try{const saved=localStorage.getItem(key);if(saved)data=validate(JSON.parse(saved));}catch(e){$('#storage').textContent='Could not load saved data; import a backup if needed.';}
function validate(d){if(!d||d.version!==1||!['sessions','courses','tasks','plans','topics','rewards'].every(k=>Array.isArray(d[k]))||!Number.isFinite(d.goal)||d.goal<1)throw Error('Invalid backup');
for(const a of ['sessions','courses','tasks','plans','topics','rewards'])if(d[a].length>10000)throw Error('Backup too large');
if(d.sessions.some(s=>!Number.isInteger(s.minutes)||s.minutes<1||s.minutes>1440||!activities.includes(s.activity)||typeof s.target!=='string'||typeof s.topic!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s.date)))throw Error('Invalid sessions');
if(d.courses.some(c=>typeof c.id!=='string'||typeof c.name!=='string'||!Number.isInteger(c.total)||c.total<1||!Number.isInteger(c.done)||c.done<0||c.done>c.total))throw Error('Invalid courses');
return d;}
function save(){try{localStorage.setItem(key,JSON.stringify(data));$('#storage').textContent='Saved on this browser';return true;}catch(e){$('#storage').textContent='Saving failed — export a backup now.';toast('Browser storage is unavailable. Export your data before leaving.');return false;}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4500);}
const date=d=>{const v=d||new Date();return v.getFullYear()+'-'+String(v.getMonth()+1).padStart(2,'0')+'-'+String(v.getDate()).padStart(2,'0');};
const today=()=>date(),uid=()=>crypto.randomUUID(),sum=s=>s.reduce((n,x)=>n+x.minutes,0);
function monday(s=today()){const d=new Date(s+'T12:00:00');d.setDate(d.getDate()-(d.getDay()+6)%7);return date(d);}
const pages={dashboard:'Dashboard',subjects:'Subjects',planner:'Study planner',focus:'Focus timer',tasks:'Assignments & exams',history:'Study history',rewards:'Rewards',courses:'Courses & MOOCs'};
$('#nav').innerHTML=Object.entries(pages).map(([k,v])=>'<a href="#'+k+'">'+v+'</a>').join('');
const targets=()=>subjects.map(s=>'<option value="'+s+'">'+s+'</option>').join('')+data.courses.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+' (course)</option>').join('');
const name=t=>subjects.includes(t)?t:data.courses.find(c=>c.id===t)?.name||'Archived course';
const cls=t=>colours[subjects.indexOf(t)]||'course';
const bar=(n,max)=>'<div class="bar"><span style="width:'+Math.min(100,Math.max(0,n/max*100))+'%"></span></div>';
const level=x=>Math.floor(x/250)+1;
function xp(){const days=[...new Set(data.sessions.map(s=>s.date))];const weeks=[...new Set(data.sessions.map(s=>monday(s.date)))];return sum(data.sessions)+days.filter(d=>sum(data.sessions.filter(s=>s.date===d))>=20).length*20+weeks.filter(w=>sum(data.sessions.filter(s=>monday(s.date)===w))>=data.goal).length*50;}
const empty=t=>'<p class="empty">'+t+'</p>';
function entries(list){return list.length?list.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(s=>'<div class="entry row"><div><span class="pill '+cls(s.target)+'">'+esc(name(s.target))+'</span> <strong>'+esc(s.topic)+'</strong><p class="muted">'+esc(s.activity)+' · '+esc(s.date)+' · '+s.minutes+' min</p>'+(s.notes?'<p>'+esc(s.notes)+'</p>':'')+'</div><button class="quiet" data-delete-session="'+esc(s.id)+'" aria-label="Delete session">×</button></div>').join(''):empty('Your next session starts the story.');}
let timer={running:false,start:0,elapsed:0};
function elapsed(){return timer.elapsed+(timer.running?Date.now()-timer.start:0);}
function timerDisplay(){const sec=Math.floor(elapsed()/1000);const el=$('#clock');if(el)el.textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');}
setInterval(timerDisplay,500);
function render(){
const parts=(location.hash.slice(1)||'dashboard').split('/'),page=pages[parts[0]]?parts[0]:'dashboard',detail=parts[1];
$('#title').textContent=pages[page];document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+page));
let out='',week=data.sessions.filter(s=>monday(s.date)===monday()),total=xp();
if(page==='dashboard')out='<section class="card hero"><span class="pill">ONE STEP AT A TIME</span><h2>Make room for your next stride.</h2><p>Choose a topic. Give it a little focus. Watch your progress grow.</p><button data-open-log>Log your first or next session →</button></section><div class="grid three"><div class="card"><p class="muted">This week</p><div class="stat">'+sum(week)+' <small>min</small></div>'+bar(sum(week),data.goal)+'<p>'+data.goal+' minute weekly goal</p></div><div class="card"><p class="muted">Your overall level</p><div class="stat">Level '+level(total)+'</div>'+bar(total%250,250)+'<p>'+total+' XP · '+(250-total%250)+' to next level</p></div><div class="card"><p class="muted">Today’s quest</p><h2>Find your focus</h2><p>Study for 20 minutes today. Earn 20 bonus XP.</p>'+bar(sum(data.sessions.filter(s=>s.date===today())),20)+'</div></div><div class="grid three">'+subjectCards()+'</div><div class="card"><h2>Coming up</h2>'+taskList(data.tasks.filter(t=>!t.done).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4))+'</div>';
if(page==='subjects'){const s=subjects.find(x=>x===decodeURIComponent(detail||''));if(s){let sessions=data.sessions.filter(x=>x.target===s);out='<a class="link" href="#subjects">← All subjects</a><div class="card '+cls(s)+'"><h2>'+s+'</h2><div class="stat">'+sum(sessions)+' min</div><p>Level '+level(sum(sessions))+' · '+sum(sessions)+' subject XP</p></div><div class="grid two"><div class="card"><h2>How you study</h2>'+activities.map(a=>'<p>'+a+' · '+sum(sessions.filter(x=>x.activity===a))+' min</p>'+bar(sum(sessions.filter(x=>x.activity===a)),Math.max(1,sum(sessions)))).join('')+'</div><div class="card"><h2>Topics & goals</h2><form id="topic-form"><input name="title" placeholder="Add a topic or learning goal" required maxlength="120"><input type="hidden" name="subject" value="'+s+'"><button>Add topic</button></form>'+data.topics.filter(t=>t.subject===s).map(t=>'<div class="entry"><label><input type="checkbox" data-topic="'+t.id+'" '+(t.done?'checked':'')+'> '+esc(t.title)+'</label></div>').join('')+'</div></div><div class="card"><h2>Subject sessions</h2>'+entries(sessions)+'</div>';}else out='<div class="grid three">'+subjectCards()+'</div>';}
if(page==='history')out='<div class="card"><div class="grid two"><label>Subject or course<select id="filter-target"><option value="">All subjects & courses</option>'+targets()+'</select></label><label>Activity<select id="filter-activity"><option value="">All activities</option>'+activities.map(a=>'<option>'+a+'</option>').join('')+'</select></label></div><label>Search topic<input id="filter-topic" placeholder="Find a topic"></label><div id="history-list">'+entries(data.sessions)+'</div></div>';
if(page==='focus')out='<div class="card"><h2>A little space to focus</h2><p class="muted">The timer counts study time. Pause it during breaks. Keep this tab open while timing.</p><div id="clock" class="timer">00:00</div><div class="actions"><button id="timer-toggle">'+(timer.running?'Pause':'Start / resume')+'</button><button id="timer-save">Finish & log</button><button class="quiet" id="timer-reset">Reset</button></div></div>';
if(page==='planner'){const start=new Date(monday()+'T12:00:00');out='<div class="card"><h2>Your week · '+monday()+'</h2><div class="week">'+Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);const ds=date(d);return '<div class="day"><strong>'+d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric'})+'</strong>'+data.plans.filter(p=>p.date===ds).map(p=>'<p class="'+cls(p.target)+'">'+esc(name(p.target))+'<br>'+esc(p.topic)+' · '+p.minutes+' min <button class="quiet" data-delete-plan="'+p.id+'">×</button></p>').join('')+'</div>';}).join('')+'</div></div><div class="card"><h2>Plan a session</h2><form id="plan-form"><div class="grid two"><label>Subject / course<select name="target">'+targets()+'</select></label><label>Date<input type="date" name="date" required value="'+today()+'"></label><label>Topic<input name="topic" required maxlength="120"></label><label>Minutes<input name="minutes" type="number" min="1" max="1440" value="30" required></label></div><button>Add to planner</button></form><h3>All planned sessions</h3>'+data.plans.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(p=>'<div class="entry row"><span>'+esc(p.date)+' · '+esc(name(p.target))+' · '+esc(p.topic)+' · '+p.minutes+' min</span><button class="quiet" data-delete-plan="'+p.id+'">Remove</button></div>').join('')+'</div>';}
if(page==='tasks')out='<div class="card"><h2>Make deadlines feel manageable</h2><form id="task-form"><div class="grid two"><label>Title<input name="title" required maxlength="160"></label><label>Subject / course<select name="target">'+targets()+'</select></label><label>Deadline<input name="date" type="date" required></label><label>Type<select name="type"><option>Assignment</option><option>Exam</option></select></label><label>Priority<select name="priority"><option>Normal</option><option>High</option><option>Low</option></select></label></div><button>Add deadline</button></form></div><div class="card">'+taskList(data.tasks.slice().sort((a,b)=>a.date.localeCompare(b.date)))+'</div>';
if(page==='courses')out='<div class="card hero"><h2>Curiosity goes beyond the classroom.</h2><p>Your online courses and MOOCs have their own home here.</p><strong>'+sum(data.sessions.filter(s=>!subjects.includes(s.target)))+' minutes of independent learning</strong></div><div class="card"><h2>Add a course</h2><form id="course-form"><div class="grid two"><label>Course name<input name="name" required maxlength="160"></label><label>Provider<input name="provider" maxlength="120"></label><label>Course link<input name="url" type="url" placeholder="https://"></label><label>Total modules<input name="total" type="number" min="1" max="10000" value="10" required></label></div><button>Add course</button></form></div>'+data.courses.map(c=>'<div class="card course"><div class="row"><h2>'+esc(c.name)+'</h2><span class="pill">'+c.done+'/'+c.total+' modules</span></div><p>'+esc(c.provider)+'</p>'+bar(c.done,c.total)+(safeUrl(c.url)?'<a class="link" href="'+esc(c.url)+'" target="_blank" rel="noopener noreferrer">Open course ↗</a>':'')+'<form data-course="'+c.id+'"><div class="grid two"><label>Completed modules<input name="done" type="number" min="0" max="'+c.total+'" value="'+c.done+'" required></label><label>Certificate link (optional)<input name="certificate" type="url" value="'+esc(c.certificate||'')+'"></label></div><button>Update progress</button></form>'+(safeUrl(c.certificate)?'<p><a class="link" href="'+esc(c.certificate)+'" target="_blank" rel="noopener noreferrer">View certificate ↗</a></p>':'')+'<p>'+sum(data.sessions.filter(s=>s.target===c.id))+' study minutes</p></div>').join('');
if(page==='rewards'){out='<div class="card hero"><h2>Every session is a step forward.</h2><div class="stat">Level '+level(total)+' · '+total+' XP</div>'+bar(total%250,250)+'<p>250 XP per level. Study minutes earn XP, plus 20 XP for each day with 20 minutes and 50 XP for each week meeting your goal.</p><p>Bonuses are calculated from your saved sessions and current goal. No penalty for missed days.</p></div><div class="grid three">'+badges().map(([n,d,ok])=>'<div class="card '+(ok?'green':'locked')+'"><span class="pill">'+(ok?'✦ Unlocked':'◇ In progress')+'</span><h2>'+n+'</h2><p>'+d+'</p></div>').join('')+'</div><div class="card"><h2>Your weekly goal</h2><form id="goal-form"><label>Minutes per week<input name="goal" type="number" min="1" max="10080" value="'+data.goal+'" required></label><button>Save goal</button></form><h2>Something to look forward to</h2><form id="reward-form"><label>Personal reward<input name="title" required maxlength="160" placeholder="A film night"></label><label>At level<input name="level" type="number" min="2" max="10000" value="5" required></label><button>Add reward</button></form>'+data.rewards.map(r=>'<div class="entry">'+esc(r.title)+' · Level '+r.level+' · '+(level(total)>=r.level?'Available!':'Keep going')+'</div>').join('')+'</div>';}
$('#content').innerHTML=out;timerDisplay();bind(page);}
function safeUrl(u){try{return ['http:','https:'].includes(new URL(u).protocol);}catch{return false;}}
function subjectCards(){return subjects.map(s=>{const n=sum(data.sessions.filter(x=>x.target===s));return '<div class="card '+cls(s)+'"><span class="pill">SCHOOL SUBJECT</span><h2>'+s+'</h2><div class="stat accent">'+n+' <small>min</small></div><p>Level '+level(n)+'</p><a class="link" href="#subjects/'+s+'">Explore subject →</a></div>';}).join('');}
function taskList(ts){return ts.length?ts.map(t=>'<div class="entry row"><label><input type="checkbox" data-task="'+esc(t.id)+'" '+(t.done?'checked':'')+'> '+esc(t.title)+'<span class="muted">'+esc(name(t.target))+' · '+esc(t.type)+' · '+esc(t.date)+' · '+esc(t.priority)+'</span></label><button class="quiet" data-delete-task="'+esc(t.id)+'">Remove</button></div>').join(''):empty('No deadlines yet. Add one when you’re ready.');}
function badges(){const s=data.sessions;const weeks=[...new Set(s.map(x=>monday(x.date)))];let topics=new Map();s.forEach(x=>{const k=x.target+'|'+x.topic.trim().toLowerCase();if(!topics.has(k))topics.set(k,new Set());topics.get(k).add(x.date);});return [['First Steps','Log your first session',s.length>0],['Paper Trail','Complete 5 past paper sessions',s.filter(x=>x.activity==='Past papers').length>=5],['Total Recall','Complete 10 flashcard sessions',s.filter(x=>x.activity==='Flashcards').length>=10],['Balanced Week','Study all 3 school subjects in one week',weeks.some(w=>subjects.every(t=>s.some(x=>x.target===t&&monday(x.date)===w)))],['Topic Revisited','Study a topic on 3 distinct dates',[...topics.values()].some(v=>v.size>=3)],['Five Hours Strong','Log 300 study minutes',sum(s)>=300],['Course Complete','Complete every module in an online course',data.courses.some(c=>c.done===c.total)]];}
let fromTimer=false;
function openLog(minutes){const f=$('#session');f.reset();f.elements.target.innerHTML=targets();f.elements.date.value=today();f.elements.date.max=today();f.elements.minutes.value=minutes||30;fromTimer=!!minutes;$('#dialog').showModal();}
$('#log').onclick=()=>openLog();$('#cancel').onclick=()=>$('#dialog').close();
$('#session').onsubmit=e=>{e.preventDefault();const f=e.target, v=Object.fromEntries(new FormData(f));if(v.date>today()||!v.topic.trim())return toast('Choose today or an earlier date and enter a topic.');const before=xp();data.sessions.push({...v,id:uid(),topic:v.topic.trim(),minutes:Number(v.minutes)});save();if(fromTimer)timer={running:false,start:0,elapsed:0};$('#dialog').close();render();toast('Session saved · +'+(xp()-before)+' XP ✨');};
function form(id,fn){const f=$(id);if(f)f.onsubmit=e=>{e.preventDefault();fn(Object.fromEntries(new FormData(f)));save();render();};}
function bind(page){
document.querySelectorAll('[data-open-log]').forEach(b=>b.onclick=()=>openLog());
for(const [attr,arr] of [['delete-session','sessions'],['delete-plan','plans'],['delete-task','tasks']])document.querySelectorAll('[data-'+attr+']').forEach(b=>b.onclick=()=>{if(!confirm('Remove this record?'))return;data[arr]=data[arr].filter(x=>x.id!==b.getAttribute('data-'+attr));save();render();});
for(const [attr,arr] of [['task','tasks'],['topic','topics']])document.querySelectorAll('[data-'+attr+']').forEach(b=>b.onchange=()=>{const x=data[arr].find(x=>x.id===b.getAttribute('data-'+attr));if(x)x.done=b.checked;save();});
form('#topic-form',v=>data.topics.push({...v,id:uid(),done:false}));form('#task-form',v=>data.tasks.push({...v,id:uid(),done:false}));form('#plan-form',v=>data.plans.push({...v,id:uid(),minutes:Number(v.minutes)}));form('#course-form',v=>data.courses.push({...v,id:uid(),total:Number(v.total),done:0,certificate:''}));form('#goal-form',v=>data.goal=Number(v.goal));form('#reward-form',v=>data.rewards.push({...v,id:uid(),level:Number(v.level)}));
document.querySelectorAll('[data-course]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const c=data.courses.find(c=>c.id===f.dataset.course),v=Object.fromEntries(new FormData(f));c.done=Number(v.done);c.certificate=v.certificate;save();render();});
if(page==='history'){const filter=()=>$('#history-list').innerHTML=entries(data.sessions.filter(s=>(!$('#filter-target').value||s.target===$('#filter-target').value)&&(!$('#filter-activity').value||s.activity===$('#filter-activity').value)&&s.topic.toLowerCase().includes($('#filter-topic').value.toLowerCase())));['#filter-target','#filter-activity','#filter-topic'].forEach(s=>$(s).oninput=filter);}
if(page==='focus'){$('#timer-toggle').onclick=()=>{if(timer.running){timer.elapsed=elapsed();timer.running=false;}else{timer.start=Date.now();timer.running=true;}render();};$('#timer-reset').onclick=()=>{if(confirm('Reset timer?')){timer={running:false,start:0,elapsed:0};render();}};$('#timer-save').onclick=()=>{const mins=Math.floor(elapsed()/60000);if(mins<1)return toast('Study for at least one minute before logging.');if(timer.running){timer.elapsed=elapsed();timer.running=false;}openLog(Math.min(1440,mins));render();};}}
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='stride-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10000000)throw Error('Too large');const incoming=validate(JSON.parse(await file.text()));if(confirm('Replace current records with this backup? Export your current records first if you want to keep them.')){data=incoming;save();render();toast('Backup restored.');}}catch{toast('This file is not a valid Stride backup.');}e.target.value='';};
addEventListener('hashchange',render);addEventListener('beforeunload',e=>{if(elapsed()>0){e.preventDefault();e.returnValue='';}});render();
